# Generated by Django 3.1.2 on 2020-11-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_card_profile'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cards',
            field=models.ManyToManyField(to='dashboard.Card'),
        ),
    ]
