# Generated by Django 3.1.2 on 2020-11-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_user',
            field=models.CharField(choices=[('admin', 'admin'), ('medium', 'medium'), ('basic', 'basic')], max_length=255, null=True),
        ),
    ]
