# Generated by Django 3.1.2 on 2020-11-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('iconClass', models.TextField(default='')),
                ('url', models.URLField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('profile', models.ManyToManyField(to='login.Profile')),
            ],
        ),
    ]
