# Generated by Django 3.1.2 on 2020-11-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='profile',
        ),
    ]
